spring.application.name=auction-case-study

# Server configuration
server.port=8080

#Security
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://dev-6mby66cjrp7o6423.us.auth0.com/.well-known/jwks.json

#SpringData MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=mydatabase
spring.data.mongodb.username=root
spring.data.mongodb.password=123456
spring.data.mongodb.authentication-database=admin