spring.application.name=auction-case-study


#Security
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://dev-6mby66cjrp7o6423.us.auth0.com/.well-known/jwks.json

#SpringData MongoDB
#spring.data.mongodb.host=mongoserver1.example.com
#spring.data.mongodb.port=27017
#spring.data.mongodb.additional-hosts[0]=mongoserver2.example.com:23456
#spring.data.mongodb.database=test
#spring.data.mongodb.username=user
#spring.data.mongodb.password=secret